controller:
  N: 20
  Q:
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 10000
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 1
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 0
    - 1
  R:
  - - 0.1
  discrete: true
  dt: 0.1
  q: 10
  r: 100.0
model:
  Cf: null
  Cr: null
  I_z: 294
  m: 180
  max_steering_angle: 0.8
  max_steering_rate: 1.6
  wbase: 1.53
  x_cg: 0.57
